apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ldmm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ldmm
    app.kubernetes.io/part-of: tkrw-pr714-0075-0018-app
  name: devfile-sample-ldmm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ldmm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ldmm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0018-tenant/tkrw-pr714-0075-0018-app/devfile-sample-ldmm@sha256:de5b2ceb43455bac5a6670818f54b5cc84f31556ebc9013e288d8f7c2f884fe7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
