apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ldmm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0018-tenant/tkrw-pr714-0075-0018-app/devfile-sample-ldmm@sha256:de5b2ceb43455bac5a6670818f54b5cc84f31556ebc9013e288d8f7c2f884fe7
        name: my-nodejs
        resources: {}
status: {}
